model:
  dest: model.FaceRecg
  paras:
    ckpt_path: 'log/ckpt/01-13_20-35-56/last_acc_0.8693.pth'
    save_ckpt_path: log/ckpt
    embed_size: 128

data:
  batch_size: 128
  num_workers: 8
  validation:
    dest: dataset.TripletValDataset
    paras: 
      pairs_num: 10000
      align_type: 'mtcnn'
      align_size: 112, 96
