model:
  dest: model.FaceRecg
  paras:
    ckpt_path: 'checkpoints/resnet50-0676ba61.pth'
    save_ckpt_path: log/ckpt
    embed_size: 128

val_interval: 1

data:
  train_ratio: 0.85
  divide_seed: 0
  batch_size: 256
  num_workers: 8
  train:
    dest: dataset.TripletTrainDataset
    paras: 
      triplets_num: 60000
      align_type: 'mtcnn'
      align_size: 112, 96
  validation:
    dest: dataset.TripletValDataset
    paras: 
      pairs_num: 10000
      align_type: 'mtcnn'
      align_size: 112, 96

loss:
  dest: loss.TripletLoss
  paras:
    alpha: 1

optimizer:
  max_epochs: 50
  linear_epochs: 10
  min_lr: 1e-8
  max_lr: 1e-4
  base_lr: 1e-6