model:
  dest: model.FaceRecg
  paras:
    ckpt_path: 'checkpoints/resnet50-0676ba61.pth'
    save_ckpt_path: log/triplet
    max_epochs: 200
    val_interval: 1

data:
  divide_seed: 0
  batch_size: 64
  num_workers: 8
  train:
    dest: dataset.dataset.TripletTrainDataset
    paras: 
      idx_path: data/train/train_indexes.json
      triplets_num: 60000
      align_type: 'mtcnn'
      align_size: 112, 96
  validation:
    dest: dataset.dataset.TripletValDataset
    paras: 
      idx_path: data/train/val_indexes.json
      pairs_num: 5000
      align_type: 'mtcnn'
      align_size: 112, 96

loss:
  dest: loss.TripletLoss
  paras:
    alpha: 0.5

optimizer:
  lr: 1e-5
  step_size: 50
  gamma: 0.1
